### ISSUE TITLE
[Bug] Solver problem with recycle loops

### ISSUE THREAD

**Issue by DanielGapes** [DanWBR/dwsim6#667]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
I have a process flowsheet which has two recycle loops. Stable operation in all versions up to the latest release v8.8.0. Solver no longer reaches a stable solution, times out at maximum iterations.
**To Reproduce**
Simply opening my process flow, and initial solve works. Change one variable, and solution no longer found
Report Message: "Error in 'DWSIM.Flowsheeet.Solver': The solver was unable to calculate the flowsheet within the specified timeout limit (FlowsheetSolver.vb, 1584

**Expected behavior**
Prior release (v8.7) has been stable. Solution usually found in 1-3 seconds.

**Screenshots**
![image](https://github.com/user-attachments/assets/566047c6-5b30-4599-9264-9c848dabf8d0)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 
 - version 23H2
 - 
**Additional context**

**Comment by DanWBR** [comment]
@DanielGapes the recycle logic was corrected in v8.8 to include individual compound flows. Try changing the smoothing factor (new property) of both recycle ops and see if it works.

**Comment by DanielGapes** [comment]
Thankyou. I went in and tried this, but to no success so far.

**Comment by DanielGapes** [comment]
Installed v8.8.1 and re-ran simulation. Simulation did not solve. Then clicked Legacy convergence mode for one recycle block, and the simulation solved straightaway. 
Given this, what is likely cause of the simulation not solving in "standard" mode? Something I should check for in my simulation setup? I am using Soave-Redlich-Kwong (SRK) property package, with water O2 N2 CO2 glucose components - could this be some cause of issue?
